# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-21 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=50, verbose_name='\u8d26\u53f7')),
                ('password', models.CharField(max_length=50, verbose_name='\u5bc6\u7801')),
            ],
        ),
    ]
