# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='birthday',
            field=models.CharField(default=1, max_length=20, verbose_name='\u751f\u65e5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='constellation',
            field=models.CharField(default=2, max_length=20, verbose_name='\u661f\u5ea7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='email',
            field=models.CharField(default=2, max_length=20, verbose_name='\u90ae\u7bb1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='head',
            field=models.CharField(default=1, max_length=20, verbose_name='\u5934\u50cf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='hobby',
            field=models.CharField(default=1, max_length=20, verbose_name='\u7231\u597d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='motto',
            field=models.CharField(default=1, max_length=20, verbose_name='\u7b7e\u540d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='nickname',
            field=models.CharField(default=1, max_length=20, verbose_name='\u6635\u79f0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='sex',
            field=models.CharField(default=1, max_length=20, verbose_name='\u6027\u522b'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='identification',
            field=models.CharField(max_length=20, verbose_name='\u8d26\u53f7'),
        ),
        migrations.AlterField(
            model_name='information',
            name='password',
            field=models.CharField(max_length=20, verbose_name='\u5bc6\u7801'),
        ),
    ]
