# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20170104_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('address', models.CharField(max_length=20, verbose_name='\u5e97\u94fa\u5730\u5740')),
                ('explanation', models.CharField(max_length=20, verbose_name='\u5956\u54c1\u8bf4\u660e')),
                ('money', models.IntegerField(default=0, verbose_name='\u91d1\u5e01')),
            ],
        ),
        migrations.RenameField(
            model_name='information',
            old_name='coin',
            new_name='money',
        ),
        migrations.AlterField(
            model_name='information',
            name='birthday',
            field=models.DateField(default='1970-1-1', verbose_name='\u751f\u65e5'),
        ),
    ]
