# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_auto_20170105_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.IntegerField(verbose_name='\u624b\u673a\u53f7')),
                ('code', models.CharField(max_length=6, verbose_name='\u9a8c\u8bc1\u7801')),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.FileField(upload_to='static/goods', verbose_name='\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='information',
            name='head',
            field=models.FileField(upload_to='static/head', verbose_name='\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='information',
            name='identification',
            field=models.IntegerField(verbose_name='\u8d26\u53f7'),
        ),
    ]
